---
- hosts: all
  become: True
  tasks:
  - name: install packages from repositories
    package: name="{{ item }}" state=present
    with_items: "{{ global_repo_packages }}"

  - name: install packages from external debs
    apt: deb="{{ item }}"
    with_items: "{{ global_external_packages }}"

  - name: install pip packages
    pip: name="{{ item }}"
    with_items: "{{ global_pip_packages }}"
