---
- hosts: all
  become: True
  tasks:
  - name: allow user passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ user_passwordless_sudo }} ALL='
      line: '{{ user_passwordless_sudo }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
