---
- hosts: all
  tasks:
    - name: download oh my zsh
      become_user: "{{ main_user }}"
      become: True
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh

    - name: initialize zsh configuration from omz template
      copy:
        src: ~/.oh-my-zsh/templates/zshrc.zsh-template
        dest: ~/.zshrc
        force: False

    - name: set zsh as the shell for the user
      become: True
      user:
        name: "{{ main_user }}"
        shell: "/bin/zsh"

    - name: download the powerline9k theme
      become_user: "{{ main_user }}"
      become: True
      git:
        repo: https://github.com/bhilburn/powerlevel9k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel9k

    - name: set support for 256 colors
      become_user: "{{ main_user }}"
      become: True
      lineinfile:
        dest: "~/.zshrc"
        regexp: "^export TERM="
        line: "export TERM=\"xterm-256color\""
        insertbefore: BOF

    - name: powerline9k segments
      become_user: "{{ main_user }}"
      become: True
      blockinfile:
        dest: "~/.zshrc"
        block: |
          POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv)
          POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
          POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="184"
          POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="black"
          POWERLEVEL9K_DIR_HOME_FOREGROUND="black"
          POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="black"
          POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="black"
          POWERLEVEL9K_DIR_HOME_BACKGROUND="208"
          POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="208"
          POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="208"
          POWERLEVEL9K_TIME_FOREGROUND="190"
          POWERLEVEL9K_TIME_BACKGROUND="030"

    - name: set the zsh theme
      become_user: "{{ main_user }}"
      become: True
      lineinfile:
        dest: "~/.zshrc"
        regexp: "^ZSH_THEME="
        line: "ZSH_THEME=\"{{ zsh_theme }}\""

    - name: add zsh-completions
      become_user: "{{ main_user }}"
      become: True
      git:
        repo: https://github.com/zsh-users/zsh-completions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

    - name: enable plugins
      lineinfile:
        dest: "~/.zshrc"
        regexp: "^plugins="
        line: plugins=(git zsh-completions)

    - name: enable autocompletion
      lineinfile:
        dest: "~/.zshrc"
        regexp: "autoload -U compinit && compinit"
        line: "autoload -U compinit && compinit"
